config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users

  root to: 'landing_pages#home'

  namespace :admin do
    resources :countries
    resources :transactions, only: [:index, :show] do
      get :approve, on: :member
      get :reject, on: :member
    end
  end

  scope module: :api, defaults: { format: :json }, path: 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
      }, skip: [:sessions, :password]
      resources :countries, only: :index
      resources :balances, only: :index
      resources :transactions, only: [:index] do
        post :top_up, on: :collection
        post :withdraw, on: :collection
        post :buy, on: :collection
        post :sell, on: :collection
      end
    end
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users

  validates :name, :currency_code, presence: true

  before_save :upcase_currency_code

  def upcase_currency_code
    self.currency_code.upcase!
  end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :find_country, only: [:show, :edit, :update, :destroy]

  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      flash[:notice] = "Country created successfully"
      redirect_to admin_countries_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @country.update_attributes(country_params)
      flash[:notice] = "Country updated successfully"
      redirect_to admin_country_path(@country)
    else
      render 'edit'
    end
  end

  def destroy
    @country.destroy!
    flash[:danger] = "Country deleted successfully"
    redirect_to admin_country_path
  end

  private

  def authenticate_admin!
    unless current_user.is_admin?
      flash[:alert] = "Not authorized"
      redirect_to root_path
    end
  end

  def find_country
    @country = Country.find(params[:id])
  end

  def country_params
    params.require(:country).permit(:id, :name, :currency_code)
  end
end

app/controllers/api/v1/countries_controller.rb
class Api::V1::CountriesController < Api::V1::BaseController
  skip_before_action :doorkeeper_authorize!, only: [:index]

  def index
    render json: Country.all, each_serializer: Api::V1::CountrySerializer
  end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/api/v1/countries_helper.rb
module Api::V1::CountriesHelper
end

app/views/admin/countries/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :currency_code %>
  <%= f.text_field :currency_code, class: "form-control" %>
</div>

app/views/admin/countries/edit.html.erb
<div class="admin-countries-edit-page">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="title">
          <h2>Edit <%= @country.name %></h2>
        </div>
        <div class="body-content">
          <div class="card">
            <div class="card-body">
              <%= form_for(@country, url: admin_country_path, method: :put) do |f| %>
                <%= render 'shared/errors', object: @country %>
                <%= render 'admin/countries/form', f: f %>
                <div class="form-group">
                  <%= f.submit "Update", class: "btn btn-block btn-success" %>
                  <%= link_to "Back", admin_country_path(@country), class: "btn btn-block btn-link" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/countries/index.html.erb
<div class="admin-countries-index-page">
  <div class="container">
    <div class="title">
      <h2>Countries</h2>
    </div>
    <div class="button-action">
      <%= link_to "Add new countries", new_admin_country_path, class: "btn btn-sm btn-outline-primary" %>
    </div>
    <div class="body-content">
      <div class="table-responsive">
        <%= table_for @countries, table_html: { class: "table" } do |table| %>
          <% table.column :id, header: "ID" %>
          <% table.column :name %>
          <% table.column :currency_code %>
          <% table.column data: "View", link_url: lambda { |country| admin_country_path(country) }, link_html: { class: "btn btn-block btn-sm btn-outline-primary" } %>
          <% table.column data: "Edit", link_url: lambda { |country| edit_admin_country_path(country) }, link_html: { class: "btn btn-block btn-sm btn-outline-warning" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/countries/new.html.erb
<div class="admin-countries-new-page">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="title">
          <h2>Add new country</h2>
        </div>
        <div class="body-content">
          <div class="card">
            <div class="card-body">
              <%= form_for(@country, url: admin_countries_path, method: :post) do |f| %>
                <%= render 'shared/errors', object: @country %>
                <%= render 'admin/countries/form', f: f %>
                <div class="form-group">
                  <%= f.submit "Create", class: "btn btn-block btn-success" %>
                  <%= link_to "Back", admin_countries_path, class: "btn btn-block btn-link" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/countries/show.html.erb
<div class="admin-countries-show-page">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="title">
          <h2><%= @country.name %></h2>
        </div>
        <div class="body-content">
          <div class="card">
            <div class="card-body">
              <div class="form-group">
                <strong><%= label_tag :name %></strong>
                <p>
                  <%= @country.name %>
                </p>
              </div>
              <div class="form-group">
                <strong><%= label_tag :currency_code %></strong>
                <p>
                  <%= @country.currency_code %>
                </p>
              </div>
              <div class="form-group">
                <%= link_to "Edit", edit_admin_country_path(@country), class: "btn btn-block btn-outline-warning" %>
                <%= link_to "Delete", admin_country_path(@country), method: :delete, class: "btn btn-block btn-outline-danger" %>
                <%= link_to "Back", admin_countries_path, class: "btn btn-block btn-link" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>