config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users

  root to: 'landing_pages#home'

  namespace :admin do
    resources :countries
    resources :transactions, only: [:index, :show] do
      get :approve, on: :member
      get :reject, on: :member
    end
  end

  scope module: :api, defaults: { format: :json }, path: 'api' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
      }, skip: [:sessions, :password]
      resources :countries, only: :index
      resources :balances, only: :index
      resources :transactions, only: [:index] do
        post :top_up, on: :collection
        post :withdraw, on: :collection
        post :buy, on: :collection
        post :sell, on: :collection
      end
    end
  end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :find_transaction, only: [:show, :approve, :reject]

  def index
    @transactions = Transaction.cash
  end

  def show
  end

  def approve
    Transaction.transaction do
      t = TransactionApproveService.new(@transaction)
      case @transaction.transaction_type
      when "top_up"
        # add money
        response = t.top_up
      when "withdraw"
        # deduct money
        response = t.withdraw
      end
      flash[response[:message_type]] = response[:message]
    end
    redirect_to admin_transaction_path(@transaction)
  end

  def reject
    @transaction.update(status: :rejected)
    flash[:notice] = "Transaction rejected"
    redirect_to admin_transaction_path(@transaction)
  end

  private

  def authenticate_admin!
    unless current_user.is_admin?
      flash[:alert] = "Not authorized"
      redirect_to root_path
    end
  end

  def find_transaction
    @transaction = Transaction.find(params[:id])
  end
end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController < Api::V1::BaseController

  def index
    render json: current_user.transactions.approved.order(:created_at), each_serializer: Api::V1::TransactionSerializer
  end

  def top_up
    @transaction = Transaction.new(transaction_params.merge(user_id: current_user.id, asset_type: :cash, transaction_type: :top_up, status: :pending))
    if @transaction.save
      render json: @transaction, serializer: Api::V1::TransactionSerializer, status: 200
    else
      render json: { errors: @transaction.errors }, status: 422
    end
  end

  def withdraw
    @transaction = Transaction.new(transaction_params.merge(user_id: current_user.id, asset_type: :cash, transaction_type: :withdraw, status: :pending))
    if @transaction.save
      render json: @transaction, serializer: Api::V1::TransactionSerializer, status: 200
    else
      render json: { errors: @transaction.errors }, status: 422
    end
  end

  def buy
    response = TransactionDealService.new(transaction_params.merge(user_id: current_user.id, transaction_type: :buy)).buy
    render json: response[:response], status: response[:status]
  end

  def sell
    response = TransactionDealService.new(transaction_params.merge(user_id: current_user.id, transaction_type: :sell)).sell
    render json: response[:response], status: response[:status]
  end

  private

  def transaction_params
    params.require(:transaction).permit(:transaction_type, :asset_type, :amount)
  end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/api/v1/transactions_helper.rb
module Api::V1::TransactionsHelper
end

app/views/admin/transactions/index.html.erb
<div class="admin-transactions-index-page">
  <div class="container">
    <div class="title">
      <h2>Transactions</h2>
    </div>
    <div class="body-content">
      <div class="table-responsive">
        <%= table_for @transactions, table_html: { class: "table" } do |table| %>
          <% table.column :id, header: "ID" %>
          <% table.column :user, header: "Requester", formatter: lambda { |user| user.display_name } %>
          <% table.column :asset_type, formatter: :titleize %>
          <% table.column :transaction_type, formatter: :titleize %>
          <% table.column :amount %>
          <% table.column :transaction_reference %>
          <% table.column :status, formatter: :titleize %>
          <% table.column data: "View", link_url: lambda { |transaction| admin_transaction_path(transaction) }, link_html: { class: "btn btn-block btn-sm btn-outline-primary"} %>
          <%# table.column data: "Approve", link_url: lambda { |transaction| approve_admin_transaction_path(transaction) }, link_html: { class: "btn btn-block btn-sm btn-outline-success" } %>
          <%# table.column data: "Reject", link_url: lambda { |transaction| reject_admin_transaction_path(transaction) }, link_html: { class: "btn btn-block btn-sm btn-outline-danger" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/transactions/show.html.erb
<div class="admin-countries-show-page">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="title">
          <h2>Transaction #<%= @transaction.id %></h2>
        </div>
        <div class="body-content">
          <div class="card">
            <div class="card-body">
              <div class="form-group">
                <strong><%= label_tag :requester %></strong>
                <p>
                  <%= @transaction.user.display_name %>
                </p>
              </div>
              <div class="form-group">
                <strong><%= label_tag :asset_type %></strong>
                <p>
                  <%= @transaction.asset_type.titleize %>
                </p>
              </div>
              <div class="form-group">
                <strong><%= label_tag :transaction_type %></strong>
                <p>
                  <%= @transaction.transaction_type.titleize %>
                </p>
              </div>
              <div class="form-group">
                <strong><%= label_tag :amount %></strong>
                <p>
                  <%= @transaction.amount %>
                </p>
              </div>
              <div class="form-group">
                <strong><%= label_tag :status %></strong>
                <p>
                  <%= @transaction.status.titleize %>
                </p>
              </div>
              <div class="form-group">
                <%= link_to "Approve", approve_admin_transaction_path(@transaction), class: "#{'disabled' if !@transaction.status.eql?('pending')} btn btn-block btn-outline-success" %>
                <%= link_to "Reject", reject_admin_transaction_path(@transaction), class: "#{'disabled' if !@transaction.status.eql?('pending')} btn btn-block btn-outline-danger" %>
                <%= link_to "Back", admin_transactions_path, class: "btn btn-block btn-link" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>